name: Discussão de Ideias
description: Descreva uma tarefa a ser realizada e marque os participantes.
title: "[DISCUSSAO]: "
labels: ["Discussão"]
body:
  - type: textarea
    id: todo
    attributes:
      label: Tarefas
      description: O que precisa ser feito?
      placeholder: "Criar um banner com uma torradeira com óculos escuro e bem maneira. \nTarefa deve ser realizada utilizando somente a imaginação."
      
    validations:
      required: true
