name: Teste de Templates
description: Descrição do template.
title: "Texto predefinido: "
labels: ["TODO"]
body:
  - type: textarea
    id: todo
    attributes:
      label: Tarefas
      description: O que precisa ser feito?
      placeholder: Criar um banner com uma torradeira com óculos escuro e bem maneira. 
    validations:
      required: true
  - type: textarea
    id: testRender
    attributes:
    label: Renderizador predefinido.
    description: "Trecho de código:"
    value: |
      1.
      2.
      3.
      ...
    render: bash
    validations:
      required: true
