name: Tarefa a ser realizada
description: File a bug report.
title: "[TODO]: "
labels: ["TODO"]
body:
  - type: markdown
    attributes:
      value: |
        Thanks for taking the time to fill out this bug report!
  - type: textarea
    id: todo
    attributes:
      label: Tarefas
      description: O que precisa ser feito?
      placeholder: Criar um banner com uma torradeira com óculos escuro e bem maneira. 
    validations:
      required: true